name: dash_bubble
description: Dash Bubble is a flutter plugin that allows you to create a floating bubble on the screen.
version: 2.5.0
repository: https://github.com/adityadand/dash_bubble
issue_tracker: https://github.com/adityadand/dash_bubble/issues
screenshots:
  - description: Dash Bubble Example GIF
    path: doc/assets/animated_example.webp

environment:
  sdk: '>=3.2.0 <4.0.0'  # Update from >=2.17.0
  flutter: ">=3.16.0"    # Update from >=3.3.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  plugin:
    platforms:
      android:
        package: dev.moaz.dash_bubble
        pluginClass: DashBubblePlugin
